project:
  type: website
  output-dir: docs
  resources:
    - "images/twitter-card.png"
  render:
    - "*.qmd"
    - "!materials/exercises"

website:
  page-navigation: true
  title: "Spatiotemporal Workshop"
  description: "Spatiotemporal Models with VAST and sdmTMB for Index Standardization of Western ABFT"
  site-url: "https://spatiotemporalmodels-workshop-abft.netlify.app/"
  
  repo-url: https://spatiotemporalmodels-workshop-abft.netlify.app
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@SostheneAkia"
    image: "/images/twitter-card.png"

  favicon: "/images/favicon.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2025"
    background: "#D4EEE5"

  navbar:
    background: "#D4EEE5"
    logo: "images/logo.png"
    pinned: true
    align: center
    right:
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/SostheneA/ST_Workshop
        text: GitHub
    left:
      - text: Home
        href: index.qmd
      - text: Prework
        href: prework.qmd
      - text: Schedule & Slides
        href: schedule.qmd
      - text: Resources
        href: resources.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Asap SemiCondensed"

editor: visual
