project:
  type: website
  output-dir: docs
  resources:
    - "images/twitter-card.png"
  render:
    - "*.qmd"
    - "!materials/exercises"

website:
  page-navigation: true
  title: "Home"
  description: "Spatiotemporal Models with VAST and sdmTMB for Index Standardization of Western ABFT"
  site-url: "https://sosthenea.github.io/ST_Workshop//"
  
  repo-url: https://sosthenea.github.io/ST_Workshop/
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@SostheneAkia"
    image: "/images/twitter-card.png"

  #favicon: "/images/logo1.jpg"

  page-footer:
    left: "This page is built by Sosthene AKIA with [Quarto](https://quarto.org/), inspired by the work of [Dr Cédric Scherer](https://posit-conf-2023.github.io/dataviz-storytelling/)."
    right: "&copy; Copyright 2026"
    background: "#219EBC"

  navbar:
    background: "#219EBC"
    #logo: "images/logo1.jpg"
    pinned: true
    align: center
    right:
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/SostheneA/ST_Workshop
        text: GitHub
    left:
      - text: Prework
        href: prework.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Slides
        href: Slide.qmd
      - text: Resources
        href: resources.qmd
        
        
  sidebar:
    - id: schedule-sidebar
      contents:
        - section: "Workshop Schedule"
          contents:
            - text: "Weekly Outlook"
              href: schedule.qmd
            - text: "Day 1: Foundations"
              href: day1.qmd
            - text: "Day 2: S-T Fusion"
              href: day2.qmd
            - text: "Day 3: VAST"
              href: day3.qmd
            - text: "Day 4: sdmTMB"
              href: day4.qmd
            - text: "Day 5: tinyVAST"
              href: day5.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Asap SemiCondensed"
